### ISSUE TITLE
[awx] chart deleted

### ISSUE THREAD

**Issue by araji** [novumrgi/helm#13]
Hi @luhahn ,

what happened to the helm chart ? just realized that it was totally removed and looked around for the reason or the new home but could not find any.

Best.
-Raji

**Comment by luhahn** [comment]
Hi there,

since there are a lot of updates for AWX I’ve decided to end support, since the Chart had it’s flaws anyways.

However the true reason why i ended the Chart is, that there is now an awx Operator, which works much better than my old helm Chart. Even the newest AWX versions are supported here. Plus the Operator is maintained from ansible directly ??

https://github.com/ansible/awx-operator

However, if you want to i can reupload the latest Version of the Chart into the repo again.

Best regards,
Lucas

Von: ***@***.***>
Gesendet: Donnerstag, 11. März 2021 11:39
An: ***@***.***>
Cc: Lucas ***@***.***>; ***@***.***>
Betreff: [novumrgi/helm] [awx] chart deleted (#13)


Hi @luhahn<https://github.com/luhahn> ,

what happened to the helm chart ? just realized that it was totally removed and looked around for the reason or the new home but could not find any.

Best.
-Raji

**Comment by araji** [comment]
no worries and thanks for the instantaneous response , much appreciated .

looking to stay with helm for now but will keep an eye on the redhat/ansible operator .

Thanks again .

Best.
-Raji

**Comment by HuangBingFeng** [comment]
Hello, can you please share the awx helm chart with me?
This is my mailbox ccqoo0233@gmail.com
If the tone is offensive, please forgive me

**Comment by luhahn** [comment]
Hi all, I've readded the helm chart for AWX since a few users are still using it. Still I recommend using the operator :)

**Comment by HuangBingFeng** [comment]
tks a lot !!!!!! And thank you also for your suggestions!  <3

Lucas Hahn ***@***.***> 於 2021年4月14日 週三 下午3:45寫道：
